# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: web_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "WebMessage.Request" do
    optional :type, :enum, 1, "WebMessage.Request.Type"
    optional :target_device_id, :string, 2
    optional :state, :string, 3
  end
  add_enum "WebMessage.Request.Type" do
    value :ALTER_STATE, 0
    value :LIST_DEVICES, 1
  end
  add_message "WebMessage.Response" do
    repeated :devices, :message, 1, "WebMessage.Response.Device"
  end
  add_message "WebMessage.Response.Device" do
    optional :id, :string, 1
    optional :state, :string, 2
    optional :name, :string, 3
    optional :state_kind, :enum, 4, "WebMessage.Response.Device.StateKind"
    optional :kind, :enum, 5, "WebMessage.Response.Device.Kind"
  end
  add_enum "WebMessage.Response.Device.StateKind" do
    value :BOOL, 0
    value :INT, 1
    value :DECIMAL, 2
  end
  add_enum "WebMessage.Response.Device.Kind" do
    value :SENSOR, 0
    value :ACTUATOR, 1
  end
end

module WebMessage
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Request").msgclass
  Request::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Request.Type").enummodule
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Response").msgclass
  Response::Device = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Response.Device").msgclass
  Response::Device::StateKind = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Response.Device.StateKind").enummodule
  Response::Device::Kind = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Response.Device.Kind").enummodule
end
