# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: web_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "WebMessage.Request" do
    optional :type, :enum, 1, "WebMessage.Request.Type"
    optional :target_device_id, :string, 2
    optional :state, :string, 3
  end
  add_enum "WebMessage.Request.Type" do
    value :ALTER_STATE, 0
    value :LIST_DEVICES, 1
  end
  add_message "WebMessage.Response" do
    optional :body, :string, 1
  end
end

module WebMessage
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Request").msgclass
  Request::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Request.Type").enummodule
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("WebMessage.Response").msgclass
end
